// Database schema types (will be generated by Prisma later)
// For now, placeholder for manual schema definitions

export interface MAACExperimentalData {
  id: number;
  experimentId: string;
  sessionId: string;
  trialId: string;
  configId: string;

  // Experimental design
  domain: string;
  tier: string;
  repetition: number;
  modelId: string;

  // Tool configuration
  enabledTools: string[];
  toolCount: number;

  // Response data
  mimicResponseText: string;
  wordCount: number;
  processingMetadata: any; // JSONB
  cognitiveCyclesCount: number;
  memoryOperationsCount: number;
  toolsInvokedCount: number;
  processingTime: number;

  // MAAC scores
  maacCognitiveLoad: number;
  maacToolExecution: number;
  maacContentQuality: number;
  maacMemoryIntegration: number;
  maacComplexityHandling: number;
  maacHallucinationControl: number;
  maacKnowledgeTransfer: number;
  maacProcessingEfficiency: number;
  maacConstructValidity: number;
  maacOverallScore: number;
  maacConfidence: number;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
  mimicStartedAt?: Date;
  mimicCompletedAt?: Date;
  maacCompleted: boolean;
}

// Legacy types for backward compatibility
export interface DatabaseModel {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface User extends DatabaseModel {
  email: string;
  name: string;
  role: 'admin' | 'researcher' | 'viewer';
}

export interface Experiment extends DatabaseModel {
  name: string;
  description: string;
  status: 'draft' | 'active' | 'completed' | 'archived';
  userId: string;
}

export interface ExperimentData extends DatabaseModel {
  experimentId: string;
  data: Record<string, unknown>;
  metadata?: Record<string, unknown>;
}

export * from './index';
