packages:
  - 'packages/*'
  - 'apps/*'
  # MIMIC cognitive engine (private repo - clone separately)
  # To enable: clone your private MIMIC repo into packages/mimic-cognitive-engine
  # Then run: pnpm install
