-- AlterTable
ALTER TABLE "maac_experiment_scenarios" ADD COLUMN     "analyzer_version" TEXT,
ADD COLUMN     "campbell_conflicting_interdep" BOOLEAN,
ADD COLUMN     "campbell_multiple_outcomes" BOOLEAN,
ADD COLUMN     "campbell_multiple_paths" BOOLEAN,
ADD COLUMN     "campbell_outcome_count" INTEGER,
ADD COLUMN     "campbell_path_count" INTEGER,
ADD COLUMN     "campbell_type" INTEGER,
ADD COLUMN     "campbell_uncertainty_level" TEXT,
ADD COLUMN     "complexity_confidence" DECIMAL(3,2),
ADD COLUMN     "complexity_overall_score" DECIMAL(5,2),
ADD COLUMN     "complexity_predicted_tier" TEXT,
ADD COLUMN     "complexity_score_json" JSONB,
ADD COLUMN     "complexity_tier_match" BOOLEAN,
ADD COLUMN     "interactivity_dependency_depth" INTEGER,
ADD COLUMN     "interactivity_dependency_edges" INTEGER,
ADD COLUMN     "interactivity_ratio" DECIMAL(3,2),
ADD COLUMN     "interactivity_simultaneous_elems" INTEGER,
ADD COLUMN     "interactivity_total_elements" INTEGER,
ADD COLUMN     "liu_li_action_complexity" INTEGER,
ADD COLUMN     "liu_li_ambiguity" DECIMAL(3,2),
ADD COLUMN     "liu_li_incongruity" DECIMAL(3,2),
ADD COLUMN     "liu_li_novelty" TEXT,
ADD COLUMN     "liu_li_relationships" DECIMAL(3,2),
ADD COLUMN     "liu_li_size" INTEGER,
ADD COLUMN     "liu_li_time_pressure" TEXT,
ADD COLUMN     "liu_li_unreliability" DECIMAL(3,2),
ADD COLUMN     "liu_li_variability" DECIMAL(3,2),
ADD COLUMN     "liu_li_variety" DECIMAL(3,2),
ADD COLUMN     "regeneration_attempts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "rejection_reasons" TEXT[],
ADD COLUMN     "score_campbell" DECIMAL(5,2),
ADD COLUMN     "score_interactivity" DECIMAL(5,2),
ADD COLUMN     "score_liu_li" DECIMAL(5,2),
ADD COLUMN     "score_wood" DECIMAL(5,2),
ADD COLUMN     "validation_duration_ms" INTEGER,
ADD COLUMN     "validation_flags" JSONB,
ADD COLUMN     "validation_passed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "validation_timestamp" TIMESTAMP(3),
ADD COLUMN     "wood_component_score" DECIMAL(5,2),
ADD COLUMN     "wood_coordinative_complexity" TEXT,
ADD COLUMN     "wood_distinct_acts" INTEGER,
ADD COLUMN     "wood_dynamic_complexity" TEXT,
ADD COLUMN     "wood_information_cues_per_act" DECIMAL(4,2),
ADD COLUMN     "wood_total_elements" INTEGER;

-- CreateIndex
CREATE INDEX "maac_experiment_scenarios_validation_passed_idx" ON "maac_experiment_scenarios"("validation_passed");

-- CreateIndex
CREATE INDEX "maac_experiment_scenarios_complexity_predicted_tier_idx" ON "maac_experiment_scenarios"("complexity_predicted_tier");
